### ISSUE TITLE
How reproduce the results of the paper!

### ISSUE THREAD

**Issue by zhongzee** [naver/shine#1]
Hello, thank you for your excellent work. I have only seen the train script so far. Which script should I run to verify or reproduce the results of your paper?

**Comment by OatmealLiu** [comment]
Hi! Thank you for your interest in our paper! There is no training needed/involved by SHiNe. In the README.md file, we provided an example of running scripts to reproduce the results in the paper.

Specifically, the evaluation scripts for OvOD task are placed in `shine/scripts_local`'s `CoDet`, `Detic`, and `VLDet`, respectively. The ones for classification task are placed in `shine/scripts_local/classification`. If you wanna run it with slurm, you can simply switch `scripts_local` to `scripts_slurm`.

The train scripts under the root folder are the entry points (or `main` functions) these scripts will call out.

Best wishes!
