### ISSUE TITLE
How do I check cosine similarity?

### ISSUE THREAD

**Issue by suyongchoi** [naver/shine#7]
Hello. I want to perform detection inference. I understand that the process involves calculating the cosine similarity between the constructed nexus classifier and the ROI proposals, and then determining the class with the highest score as the correct prediction. Is it possible to directly check the cosine similarities between the constructed nexus classifier's classes and the ROI proposals using the various files you've provided? Thank you!

**Comment by OatmealLiu** [comment]
Hi! Thank you for your interest in our work. You can print or save the `scores` vectors for each proposed bbox, the `scores` vecotors are the cosine similarity between each bbox proposal w.r.t. each nexus point that is corresponding to each target class name (or say Class of Interests) of the dataset.
